# Generated by Django 5.0.7 on 2024-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0004_passticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_review', 'In Review'), ('in_revision', 'In Revision'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
