# Generated by Django 5.0.7 on 2024-08-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0007_remove_payment_case_file_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passticket',
            name='content',
        ),
        migrations.AddField(
            model_name='passticket',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='pass_tickets/'),
        ),
    ]
