# Generated by Django 5.0.7 on 2024-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0008_remove_passticket_content_passticket_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='passticket',
            name='document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pass_tickets/pdf/'),
        ),
    ]
