# Generated by Django 5.0.7 on 2024-08-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0010_rename_landlord_name_casefile_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='case_files/'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='form_type',
            field=models.CharField(choices=[('rent_restriction', 'Rent Restriction'), ('business_premises', 'Business Premises'), ('rent_tribunal', 'Rent Tribunal'), ('cooperative_tribunal', 'Cooperative Tribunal')], default='rent_restriction', max_length=30),
        ),
    ]
