# Generated by Django 5.0.7 on 2024-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0011_casefile_file_upload_casefile_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casefile',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
