# Generated by Django 5.0.7 on 2024-08-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrial', '0003_casefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytrial.casefile')),
            ],
        ),
    ]
